# Generated by Django 3.2.5 on 2021-09-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="SwipeResults",
            fields=[
                (
                    "id_swipe_session",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="id_swipe_session",
                    ),
                ),
                ("query", models.CharField(max_length=200, verbose_name="query")),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                (
                    "serialized_results",
                    models.TextField(verbose_name="serialized_results"),
                ),
            ],
        )
    ]
