# Generated by Django 3.2.5 on 2021-09-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="swiperesults",
            name="id_swipe_session",
            field=models.CharField(
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="id_swipe_session",
            ),
        )
    ]
