# Generated by Django 3.2.5 on 2021-12-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0002_alter_swiperesults_id_swipe_session")]

    operations = [
        migrations.AlterField(
            model_name="swiperesults",
            name="id_swipe_session",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="id_swipe_session",
            ),
        )
    ]
