SELECT ID,
	BEST_QUESTION
FROM PUBLIC.QUESTIONS_GPT_ARTICLES_10_CITATIONS AS T
where position('author' in BEST_QUESTION)>0
LIMIT 100





SELECT ID,
	MIN_COS_DISTANCE,
	LENGTH(BEST_QUESTION) - LENGTH(REPLACE(BEST_QUESTION, ' ', '')) -1 AS NB_WORDS,
	BEST_QUESTION,
	TT."paperAbstract" AS TLDR
FROM PUBLIC.QUESTIONS_GPT_ARTICLES_10_CITATIONS AS TT
WHERE ID in
		(SELECT T.ID
			FROM PUBLIC.QUESTIONS_GPT_ARTICLES_10_CITATIONS AS T
			LIMIT 100)
Vous avez envoyé
requete qui ne sert à rien car il faut utiliser la cosim entre abstract et best question et non pas entre tldr et best question

select *, MIN_COS_DISTANCE + 0.01 * NB_WORDS as generalscore
from
(SELECT ID,
	MIN_COS_DISTANCE,
	LENGTH(BEST_QUESTION) - LENGTH(REPLACE(BEST_QUESTION, ' ', '')) -1 AS NB_WORDS,
	BEST_QUESTION,
	TT."paperAbstract" AS TLDR
FROM PUBLIC.QUESTIONS_GPT_ARTICLES_10_CITATIONS AS TT
WHERE ID in
		(SELECT T.ID
			FROM PUBLIC.QUESTIONS_GPT_ARTICLES_10_CITATIONS AS T
			LIMIT 100)) as g




SELECT TT.ID,
	MIN_COS_DISTANCE AS MIN_COS_TLDR_QUESTION,
	BEST_QUESTION,
	TT."paperAbstract" AS TLDR,
	TTT."paperAbstract"
FROM (PUBLIC.QUESTIONS_GPT_ARTICLES_10_CITATIONS AS TT
						JOIN PUBLIC.S2ORC_ECO_QA_FULL AS TTT ON TT.ID = TTT.ID)
WHERE TT.ID in
		(SELECT T.ID
			FROM PUBLIC.QUESTIONS_GPT_ARTICLES_10_CITATIONS AS T
			LIMIT 1000)
